from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from sqlalchemy.orm import Session

from app.core.logging import log
from app.llm.router import llm_for
from app.memory import rag
from app.models import ArtifactType
from app.services import render, versioning

BANK_SYSTEM = """You are a senior business analyst at HDFC Bank, India's largest private-sector bank.
You are working inside a governed, auditable SDLC platform. Non-negotiable rules:

1. GROUND EVERYTHING. Every requirement, rule and statement must be traceable to the supplied
   evidence (meeting notes, emails, transcripts, approved upstream artifacts). If the evidence
   does not support a claim, do not make the claim.
2. NEVER INVENT. If information is missing, record it as a gap or an open question rather than
   filling it with a plausible guess. A missing requirement is recoverable; a fabricated one is not.
3. SURFACE CONFLICTS. When two sources disagree, flag the conflict for human resolution instead of
   silently picking one.
4. THINK REGULATED. This is a bank. Consider RBI guidelines, data localisation, auditability,
   AFA/authentication, and customer-consent implications wherever they are relevant.
5. BE SPECIFIC. "The system should be fast" is worthless. "p95 ≤ 2.5s at the BFF edge" is a requirement.
"""


@dataclass
class AgentContext:
    db: Session
    project_id: str
    project_name: str
    run_id: str
    state: dict[str, Any] = field(default_factory=dict)
    feedback: list[str] = field(default_factory=list)  # reviewer comments from a rejected round


@dataclass
class AgentResult:
    artifacts: dict[str, str]          # ArtifactType.value -> ArtifactVersion.id
    payloads: dict[str, Any]
    notes: str = ""
    external: dict[str, Any] = field(default_factory=dict)


class BaseAgent:
    id: str = "agent"
    name: str = "Agent"

    def __init__(self, ctx: AgentContext) -> None:
        self.ctx = ctx

    # ── helpers every agent shares ────────────────────────────────────────────
    def recall(self, query: str, namespaces: list[str], k: int = 8) -> str:
        hits = rag.retrieve(
            project_id=self.ctx.project_id, query=query, k=k, namespaces=namespaces
        )
        return rag.as_context(hits)

    def feedback_block(self) -> str:
        if not self.ctx.feedback:
            return ""
        items = "\n".join(f"- {f}" for f in self.ctx.feedback)
        return (
            "--- REVIEWER FEEDBACK FROM THE PREVIOUS ROUND (must be addressed) ---\n"
            f"{items}\n--- END REVIEWER FEEDBACK ---"
        )

    def generate(self, *, task: str, prompt: str, schema: dict, temperature: float = 0.2) -> dict:
        llm, model = llm_for(self.id)
        log.info("agent.generate", agent=self.id, task=task, run=self.ctx.run_id,
                 model=model or llm.model_name)
        return llm.generate_json(
            system=BANK_SYSTEM, prompt=prompt, schema=schema, task=task,
            model=model, temperature=temperature,
        )

    @property
    def model_used(self) -> str:
        """Recorded on every artifact version. A model-risk review asks for exactly this, and
        "an LLM" is not an acceptable answer."""
        llm, model = llm_for(self.id)
        return f"{model}" if model else llm.model_name

    def commit(
        self, atype: ArtifactType, payload: dict, *, change_summary: str = "",
        external_ref: str | None = None, index_namespace: str | None = "artifact",
    ):
        md = render.render(atype, payload)
        v = versioning.commit_version(
            db=self.ctx.db,
            project_id=self.ctx.project_id,
            atype=atype,
            payload=payload,
            rendered_md=md,
            produced_by=self.id,
            run_id=self.ctx.run_id,
            model=self.model_used,
            change_summary=change_summary or f"Generated by {self.name}",
            external_ref=external_ref,
        )
        if index_namespace:
            rag.index(
                project_id=self.ctx.project_id,
                content=md,
                namespace=index_namespace,
                source_id=v.id,
                meta={"artifact_type": atype.value, "version": v.version},
            )
        return v

    def run(self) -> AgentResult:  # pragma: no cover - interface
        raise NotImplementedError
