/**
 * Tiny markdown renderer. The markdown we render is machine-generated by
 * backend/app/services/render.py, so the grammar is closed and known: h1-h3, tables, lists,
 * bold/italic/code, links. Shipping a full markdown library to parse our own output would be
 * dead weight.
 */
const slug = (s) => s.toLowerCase().replace(/[^\w\s-]/g, '').trim().replace(/\s+/g, '-').slice(0, 60)
const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

const inline = (s) =>
  esc(s)
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/_([^_]+)_/g, '<em>$1</em>')
    // Images BEFORE links — otherwise the link rule eats ![alt](src) and leaves a stray "!".
    // That bug meant every Stitch screenshot rendered as a broken-looking hyperlink instead of a
    // picture, so a working wireframe generator looked like a broken one.
    .replace(/!\[([^\]]*)\]\(([^)]+)\)/g,
      '<img src="$2" alt="$1" loading="lazy" class="max-h-64 rounded-lg border border-line" />')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank" rel="noreferrer">$1</a>')
    .replace(/&lt;br&gt;/g, '<br>')

export function toc(md = '') {
  return md.split('\n')
    .map((l) => l.match(/^(#{2,3})\s+(.*)$/))
    .filter(Boolean)
    .map((m) => ({ level: m[1].length, text: m[2].replace(/[*_`]/g, ''), id: slug(m[2]) }))
}

export function mdToHtml(md = '') {
  const lines = md.split('\n')
  const out = []
  let i = 0
  while (i < lines.length) {
    const l = lines[i]

    if (/^\|/.test(l) && /^\|[\s:|-]+\|$/.test(lines[i + 1] || '')) {
      const cells = (r) => r.split('|').slice(1, -1).map((c) => c.trim())
      const head = cells(l)
      i += 2
      const rows = []
      while (i < lines.length && /^\|/.test(lines[i])) rows.push(cells(lines[i++]))
      out.push(
        `<div class="overflow-x-auto"><table><thead><tr>${head.map((h) => `<th>${inline(h)}</th>`).join('')}</tr></thead><tbody>` +
        rows.map((r) => `<tr>${r.map((c) => `<td>${inline(c)}</td>`).join('')}</tr>`).join('') +
        '</tbody></table></div>',
      )
      continue
    }

    const h = l.match(/^(#{1,4})\s+(.*)$/)
    if (h) { const n = h[1].length; out.push(`<h${n} id="${slug(h[2])}">${inline(h[2])}</h${n}>`); i++; continue }

    if (/^[-*]\s+/.test(l)) {
      const items = []
      while (i < lines.length && /^[-*]\s+/.test(lines[i])) items.push(`<li>${inline(lines[i++].replace(/^[-*]\s+/, ''))}</li>`)
      out.push(`<ul>${items.join('')}</ul>`)
      continue
    }
    if (/^\d+\.\s+/.test(l)) {
      const items = []
      while (i < lines.length && /^\d+\.\s+/.test(lines[i])) items.push(`<li>${inline(lines[i++].replace(/^\d+\.\s+/, ''))}</li>`)
      out.push(`<ol>${items.join('')}</ol>`)
      continue
    }
    if (l.trim()) out.push(`<p>${inline(l)}</p>`)
    i++
  }
  return out.join('\n')
}
